export type {
  FontOptions,
  FontSubset,
  FontDisplay,
  FontWeight,
  FontStyle,
  LoadedFont,
  LocalFontOptions,
  LocalFontSource,
} from "@swift-rust/font";
export {
  normalizeClassName,
  buildCssVariable,
  localFont,
  Lausanne,
  DxSlight,
  DxSlightMediumUltra,
  DxSlightExtBdUltraSlant,
  VarentGrotesk,
  VarentGroteskBold,
  VarentGroteskExtLtIta,
  Zimula,
  ALL_LOCAL_FONTS,
  ALL_LOCAL_FONT_PATHS,
  localFontCss,
  LAUSANNE_PATHS,
  DX_SLIGHT_PATHS,
  VARENT_PATHS,
  ZIMULA_PATHS,
} from "@swift-rust/font";
