export type {
  FontDisplay,
  FontOptions,
  FontStyle,
  FontSubset,
  FontWeight,
  LoadedFont,
  LocalFontOptions,
  LocalFontSource,
} from "@swift-rust/font";
export {
  ALL_LOCAL_FONT_PATHS,
  ALL_LOCAL_FONTS,
  buildCssVariable,
  DX_SLIGHT_PATHS,
  DxSlight,
  DxSlightExtBdUltraSlant,
  DxSlightMediumUltra,
  LAUSANNE_PATHS,
  Lausanne,
  localFont,
  localFontCss,
  normalizeClassName,
  VARENT_PATHS,
  VarentGrotesk,
  VarentGroteskBold,
  VarentGroteskExtLtIta,
  ZIMULA_PATHS,
  Zimula,
} from "@swift-rust/font";
