export interface ComponentInfo {
  name: string;
  files: string[];
  dependencies?: string[];
}

const COMPONENTS: Record<string, ComponentInfo> = {
  accordion: { name: "accordion", files: ["accordion.tsx"] },
  alert: { name: "alert", files: ["alert.tsx"] },
  "alert-dialog": { name: "alert-dialog", files: ["alert-dialog.tsx"] },
  "aspect-ratio": { name: "aspect-ratio", files: ["aspect-ratio.tsx"] },
  avatar: { name: "avatar", files: ["avatar.tsx"] },
  badge: { name: "badge", files: ["badge.tsx"] },
  breadcrumb: { name: "breadcrumb", files: ["breadcrumb.tsx"] },
  button: { name: "button", files: ["button.tsx"] },
  "button-group": { name: "button-group", files: ["button-group.tsx"] },
  calendar: { name: "calendar", files: ["calendar.tsx"] },
  callout: { name: "callout", files: ["callout.tsx"] },
  card: { name: "card", files: ["card.tsx"] },
  carousel: { name: "carousel", files: ["carousel.tsx"] },
  chart: { name: "chart", files: ["chart.tsx"] },
  checkbox: { name: "checkbox", files: ["checkbox.tsx"] },
  code: { name: "code", files: ["code.tsx"] },
  "code-block": { name: "code-block", files: ["code-block.tsx"] },
  collapsible: { name: "collapsible", files: ["collapsible.tsx"] },
  combobox: { name: "combobox", files: ["combobox.tsx"] },
  command: { name: "command", files: ["command.tsx"] },
  "context-menu": { name: "context-menu", files: ["context-menu.tsx"] },
  "data-table": { name: "data-table", files: ["data-table.tsx"] },
  "date-picker": { name: "date-picker", files: ["date-picker.tsx"] },
  dialog: { name: "dialog", files: ["dialog.tsx"] },
  direction: { name: "direction", files: ["direction.tsx"] },
  drawer: { name: "drawer", files: ["drawer.tsx"] },
  "dropdown-menu": { name: "dropdown-menu", files: ["dropdown-menu.tsx"] },
  empty: { name: "empty", files: ["empty.tsx"] },
  field: { name: "field", files: ["field.tsx"] },
  "file-upload": { name: "file-upload", files: ["file-upload.tsx"] },
  form: { name: "form", files: ["form.tsx"] },
  "hover-card": { name: "hover-card", files: ["hover-card.tsx"] },
  input: { name: "input", files: ["input.tsx"] },
  "input-group": { name: "input-group", files: ["input-group.tsx"] },
  "input-otp": { name: "input-otp", files: ["input-otp.tsx"] },
  item: { name: "item", files: ["item.tsx"] },
  kbd: { name: "kbd", files: ["kbd.tsx"] },
  label: { name: "label", files: ["label.tsx"] },
  menubar: { name: "menubar", files: ["menubar.tsx"] },
  "native-select": { name: "native-select", files: ["native-select.tsx"] },
  "navigation-menu": { name: "navigation-menu", files: ["navigation-menu.tsx"] },
  pagination: { name: "pagination", files: ["pagination.tsx"] },
  popover: { name: "popover", files: ["popover.tsx"] },
  progress: { name: "progress", files: ["progress.tsx"] },
  "radio-group": { name: "radio-group", files: ["radio-group.tsx"] },
  resizable: { name: "resizable", files: ["resizable.tsx"] },
  "scroll-area": { name: "scroll-area", files: ["scroll-area.tsx"] },
  select: { name: "select", files: ["select.tsx"] },
  separator: { name: "separator", files: ["separator.tsx"] },
  sheet: { name: "sheet", files: ["sheet.tsx"] },
  sidebar: { name: "sidebar", files: ["sidebar.tsx"] },
  skeleton: { name: "skeleton", files: ["skeleton.tsx"] },
  slider: { name: "slider", files: ["slider.tsx"] },
  sonner: { name: "sonner", files: ["sonner.tsx"] },
  spinner: { name: "spinner", files: ["spinner.tsx"] },
  stepper: { name: "stepper", files: ["stepper.tsx"] },
  switch: { name: "switch", files: ["switch.tsx"] },
  table: { name: "table", files: ["table.tsx"] },
  tabs: { name: "tabs", files: ["tabs.tsx"] },
  textarea: { name: "textarea", files: ["textarea.tsx"] },
  toast: { name: "toast", files: ["toast.tsx"] },
  toggle: { name: "toggle", files: ["toggle.tsx"] },
  "toggle-group": { name: "toggle-group", files: ["toggle-group.tsx"] },
  tooltip: { name: "tooltip", files: ["tooltip.tsx"] },
};

export default COMPONENTS;
